[build]
  functions = "netlify/functions"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/stockapi/*"
  status = 200
  to = "/.netlify/functions/stockapi/:splat"
